version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      FLASK_ENV: development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    volumes:
      - ./frontend:/app
